<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/marco-canas/introducci-n-al-Machine-Learning/blob/main/classes/class_9/class_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
  <td>
    <a target="_blank" href="https://kaggle.com/kernels/welcome?src=https://github.com/marco-canas/introducci-n-al-Machine-Learning/blob/main/classes/class_9/class_9.ipynb"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" /></a>
  </td>
</table> 

# Clase 9 Introducción al Machine Learning: 19 de Enero de 2022

## Participación aleatoria de los estudiantes en clase

In [9]:
def estudiante_participar():
    import numpy as np 
    import pandas as pd 

    grupo_intro_ml = pd.read_csv('grupo_intro_ml.csv', sep = ',')

    from random import randint, choice

    np.random.seed(513) 
    return choice(grupo_intro_ml.nombre)

# grupo_intro_ml.head() 

In [11]:
estudiante_participar() 

'CORRALES BOHÓRQUEZ ANGEL '

# [Numpy user guide](https://numpy.org/doc/stable/user/index.html)

In [14]:
%%time
n = 10
a = list(range(n))
b = a
c = []
for i in range(len(a)):
    c.append(a[i]*b[i])

Wall time: 0 ns


In [15]:
%%time
n = 10
a = np.arange(n)
b = a
c = a*b

Wall time: 4.01 ms


## ¿Por qué NumPy es rápido?

La vectorización describe la ausencia de bucles explícitos e indexación en el código: estas cosas están teniendo lugar, por supuesto, solo "detrás de escena" en código C optimizado y precompilado. 

El código vectorizado tiene muchas ventajas, entre las que se encuentran:

* el código vectorizado es más conciso y más fácil de leer

* menos líneas de código generalmente significa menos errores

* el código se asemeja más a la notación matemática estándar (lo que facilita, normalmente, codificar correctamente las construcciones matemáticas)

Sin vectorización, nuestro código estaría lleno de bucles `for` ineficientes y difíciles de leer.

In [16]:
a = np.array([[1., 0., 0.],
 [0., 1., 2.]])

In [17]:
a 

array([[1., 0., 0.],
       [0., 1., 2.]])

In [19]:
a.ndim     # el número de ejes (dimensiones) de la matriz.

2

In [21]:
a.shape     # las dimensiones de la matriz. Esta es una tupla de enteros que indica 
            # el tamaño de la matriz en cada dimensión. Para una matriz con n filas y m columnas, será.
            # La longitud de la tupla es, por lo tanto, el número de ejes, .shape(n,m)shapendim

(2, 3)

In [ ]:
a.size     # el número total de elementos de la matriz. Esto es igual al producto de los elementos de .shape

In [22]:
a.dtype    # un objeto que describe el tipo de elementos de la matriz. 
           # Uno puede crear o especificar dtype's usando tipos estándar de Python. 
           # Además, NumPy proporciona tipos propios. numpy.int32, numpy.int16 y numpy.float64 son algunos ejemplos.

dtype('float64')

In [23]:
a.itemsize    # el tamaño en bytes de cada elemento de la matriz. 
              # Por ejemplo, una matriz de elementos de tipo tiene 8 (=64/8), mientras que una de tipo tiene 4 (=32/8). 
              # Es equivalente a .float64itemsizecomplex32itemsizendarray.dtype.itemsize

8

In [24]:
a.data    # el búfer que contiene los elementos reales de la matriz. 
          # Normalmente, no necesitaremos usar este atributo porque accederemos a 
          # los elementos de una matriz utilizando las instalaciones de indexación.

## Otro ejemplo

In [26]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
a.shape

(3, 5)

In [28]:
a.ndim

2

In [29]:
a.dtype.name

'int32'

In [30]:
a.itemsize

4

In [31]:
a.size

15

In [32]:
type(a)

numpy.ndarray

In [ ]:
b = np.array([6, 7, 8])
b

In [33]:
type(b)


numpy.ndarray

## Creación de arreglos

Hay varias formas de crear matrices.

Por ejemplo, puede crear una matriz a partir de una lista o tupla normal de Python utilizando la función `array()`. 

El tipo de matriz resultante se deduce del tipo de elementos en las secuencias.

In [34]:
import numpy as np
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [35]:
a.dtype

dtype('int32')

In [36]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

Un error frecuente consiste en llamar a la función `array()` con múltiples argumentos, en lugar de proporcionar una sola secuencia como argumento: 

In [37]:
a = np.array(1, 2, 3, 4)    # WRONG

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [38]:

a = np.array([1, 2, 3, 4])  # RIGHT

`array()` transforma secuencias de secuencias en matrices bidimensionales, secuencias de secuencias de secuencias en matrices tridimensionales, etc.

In [2]:
import numpy as np 
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

El tipo de matriz también se puede especificar explícitamente en el momento de la creación:

In [3]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

## Creación de matrices especiales

In [9]:
np.zeros(2)

array([0., 0.])

In [10]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [12]:
np.zeros((2,2))     # Ojo, el argumento debe ser un entero un una tupla de enteros. 

array([[0., 0.],
       [0., 0.]])

In [13]:
np.zeros((2,2))     # Ojo, el argumento debe ser un entero un una lista de enteros. 

array([[0., 0.],
       [0., 0.]])

In [8]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((2, 3), dtype = np.int8)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [22]:
    
np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

## Creación de secuencias de números

Para crear secuencias de números, NumPy proporciona la función `np.arange()` que es análoga a la función `range()` de Python, pero devuelve una matriz.

## Referentes  

* Guía del usuario de Numpy: https://numpy.org/doc/stable/user/index.html