
<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/marco-canas/taca/blob/main/ref/geron/chap_2/5_prepare_for_algorithms/1_prepare_for_algorithms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
  <td>
    <a target="_blank" href="https://kaggle.com/kernels/welcome?src=https://github.com/marco-canas/taca/blob/main/ref/geron/chap_2/5_prepare_for_algorithms/1_prepare_for_algorithms.ipynb"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" /></a>
  </td>
</table> 


# Clase 8

In [49]:
import numpy as np 
import pandas as pd 
grupo_intro_ml = pd.read_csv('grupo_intro_ml.csv', sep = ',')   

from random import randint,choice 

np.random.seed(513)

lista = list(range(1,27)) 

lista_tema_asignado = []

for i in range(1,27):
    a = choice(lista)
    lista_tema_asignado.append(a)
    lista.remove(a)

grupo_intro_ml['Asignación Quiz 1'] = lista_tema_asignado

grupo_intro_ml

cedula                             nombre  \
0   1193092675      ALVAREZ CARRERO GERMAN JOSE    
1   1152715251      AMAYA ESCOBAR LILLEY DANIELA   
2   1152204969       ARANGO JARAMILLO JUAN JOSE    
3   1037657637       BOLIVAR HIGUITA JUAN PABLO    
4   1146437759             BUITRAGO LORA VANESSA   
5   1000305704             CARDONA GÓMEZ ELIANA    
6   1000756943             CARDONA ZAPATA SIMON    
7   1152686248         CORRALES BOHÓRQUEZ ANGEL    
8   1035921687      GALLEGO JARAMILLO JUAN PABLO   
9   1001748329      GIL QUINTERO LISBETH YULIZA    
10  1000653700        GIRALDO GALLEGO ANA MARÍA    
11  1152456567       GIRALDO MENA YINIM ALBERTO    
12  1010141168            GRANADA ZAPATA SUSANA    
13  1097403976         HERNANDEZ SUAREZ NICOLAS    
14  1036966621      JIMÉNEZ GARCÍA MIGUEL ÁNGEL    
15  1098823480   MARTINEZ PÉREZ PEDRO ALEJANDRO    
16  1035434122    MONTOYA GONZÁLEZ PABLO ANDRÉS    
17  1000754994           MORALES GARCÍA MANUELA    
18  1040367403    MOSQUERA PEREA JESÚS JHOVANNY    
19  1013346470      MURILLO ZAPATA MIGUEL ANGEL    
20  1214747720    NARVAEZ MONSALVE KAROL ANDREA    
21  1007813704     PULGARIN QUIROZ EMILY IVETTE    
22  1001851542   RODRIGUEZ BARRIOS DAIRA LORENA    
23  1152225691    TORRES MERIÑO JOSE LUIS CAMILO   
24  1007722578  TRUJILLO VERTEL MAIRA ALEJANDRA    
25  1017266250       ZAPATA VANEGAS JUAN CAMILO    

                             email  Asignación Quiz 1  
0      german.alvarez1@udea.edu.co                  8  
1        lilley.amaya1@udea.edu.co                  1  
2         juan.arangoj@udea.edu.co                 26  
3       jpablo.bolivar@udea.edu.co                 10  
4    vanessa.buitragol@udea.edu.co                 22  
5     eliana.cardonag1@udea.edu.co                 20  
6       simon.cardonaz@udea.edu.co                  5  
7       angel.corrales@udea.edu.co                 14  
8        juan.gallegoj@udea.edu.co                  6  
9          lisbeth.gil@udea.edu.co                 11  
10       ana.giraldo15@udea.edu.co                 13  
11       yinim.giraldo@udea.edu.co                 23  
12      susana.granada@udea.edu.co                 19  
13   nicolas.hernandez@udea.edu.co                 16  
14     miguel.jimenezg@udea.edu.co                 17  
15     pedro.martinez1@udea.edu.co                  4  
16      pabloa.montoya@udea.edu.co                 24  
17    manuela.moralesg@udea.edu.co                 25  
18   jhovanny.mosquera@udea.edu.co                 18  
19      mangel.murillo@udea.edu.co                 21  
20       karol.narvaez@udea.edu.co                 15  
21     emily.pulgarinq@udea.edu.co                 12  
22     daira.rodriguez@udea.edu.co                  9  
23  jluiscamilo.torres@udea.edu.co                  7  
24      maira.trujillo@udea.edu.co                  3  
25      juan.zapata100@udea.edu.co                  2

## [Numpy](https://numpy.org/doc/stable/user/whatisnumpy.html)

### ¿Qué es NumPy?

NumPy es el paquete fundamental para la computación científica en Python. 

Es una biblioteca de Python que proporciona un objeto de matriz multidimensional, varios objetos derivados y una variedad de rutinas para operaciones rápidas en matrices, que incluyen matemáticas, lógicas, manipulación de formas, clasificación, selección, E/S, transformadas de Fourier discretas, álgebra lineal básica, operaciones estadísticas básicas, simulación aleatoria y mucho más.

En el núcleo del paquete NumPy, se encuentra el objeto ndarray. 

Esto encapsula matrices n-dimensionales de tipos de datos homogéneos, con muchas operaciones que se realizan en código compilado para el rendimiento. 

Hay varias diferencias importantes entre las matrices NumPy y las secuencias estándar de Python:

* Las matrices NumPy tienen un tamaño fijo en la creación, a diferencia de las listas de Python (que pueden crecer dinámicamente). 

Cambiar el tamaño de un ndarray creará una nueva matriz y eliminará la original.

* Se requiere que todos los elementos de una matriz NumPy sean del mismo tipo de datos y, por lo tanto, tengan el mismo tamaño en memoria. 

* Las matrices NumPy facilitan operaciones matemáticas avanzadas y otros tipos de operaciones en grandes cantidades de datos. Por lo general, tales operaciones se ejecutan de manera más eficiente y con menos código de lo que es posible utilizando las secuencias integradas de Python.

* Una creciente plétora de paquetes científicos y matemáticos basados en Python están utilizando matrices NumPy; aunque estos suelen admitir la entrada de secuencia de Python, convierten dicha entrada en matrices NumPy antes del procesamiento y, a menudo, generan matrices NumPy. 

En otras palabras, para usar de manera eficiente gran parte (tal vez incluso la mayoría) del software científico / matemático basado en Python de hoy, solo saber cómo usar los tipos de secuencia incorporados de Python es insuficiente, uno también necesita saber cómo usar matrices NumPy.

Los puntos sobre el tamaño y la velocidad de la secuencia son particularmente importantes en la computación científica. 

Como ejemplo simple, considere el caso de multiplicar cada elemento en una secuencia 1-D con el elemento correspondiente en otra secuencia de la misma longitud. 

Si los datos se almacenan en dos listas de Python, y , podríamos iterar sobre cada elemento:`ab`

In [4]:
%%time
n = 10_000_000
a = list(range(n))
b = a
c = []
for i in range(len(a)):
    c.append(a[i]*b[i])
    

Wall time: 6.5 s


In [5]:
c[:5]

[0, 1, 4, 9, 16]

In [6]:
%%time
n = 10_000_000
import numpy as np
d=np.arange(n)
e = d
f = d*e

Wall time: 59.6 ms


In [8]:
f[:5]

array([ 0,  1,  4,  9, 16])

Esto produce la respuesta correcta, pero si y cada uno contiene millones de números, pagaremos el precio por las ineficiencias de los bucles en Python. 

Podríamos realizar la misma tarea mucho más rápidamente en C escribiendo (para mayor claridad descuidamos las declaraciones e inicializaciones de variables, la asignación de memoria, etc.)`ab`

## ¿Por qué NumPy es rápido?

La vectorización describe la ausencia de bucles explícitos, indexación, etc., en el código: estas cosas están teniendo lugar, por supuesto, solo "detrás de escena" en código C optimizado y precompilado. 

El código vectorizado tiene muchas ventajas, entre las que se encuentran:

* el código vectorizado es más conciso y más fácil de leer 
* menos líneas de código generalmente significa menos errores

* el código se asemeja más a la notación matemática estándar (lo que facilita, normalmente, codificar correctamente las construcciones matemáticas)

la vectorización da como resultado más código "Pythonic". Sin vectorización, nuestro código estaría lleno de bucles ineficientes y difíciles de leer.for

Radiodifusión es el término utilizado para describir el comportamiento implícito elemento por elemento de las operaciones; En términos generales, en NumPy todas las operaciones, no solo las operaciones aritméticas, sino lógicas, bit-wise, funcionales, etc., se comportan de esta manera implícita elemento por elemento, es decir, transmiten. Además, en el ejemplo anterior, y podrían ser matrices multidimensionales de la misma forma, o un escalar y una matriz, o incluso dos matrices de con diferentes formas, siempre que la matriz más pequeña sea "expandible" a la forma de la más grande de tal manera que la difusión resultante sea inequívoca. Para conocer las "reglas" detalladas de la radiodifusión, véase basics.broadcasting.ab

## ¿Quién más usa NumPy?

NumPy es totalmente compatible con un enfoque orientado a objetos, comenzando, una vez más, con ndarray. 

Por ejemplo, ndarray es una clase, que posee numerosos métodos y atributos. 

Muchos de sus métodos se reflejan en funciones en el espacio de nombres NumPy más externo, lo que permite al programador codificar en el paradigma que prefiera. 

Esta flexibilidad ha permitido que el dialecto de matriz NumPy y la clase NumPy ndarray se conviertan en el lenguaje de facto de intercambio de datos multidimensional utilizado en Python.

## Inicio rápido de NumPy
### Prerrequisitos
Necesitarás saber un poco de Python. Para obtener un repaso, consulte el tutorial de Python.

Para trabajar los ejemplos, necesitará instalar además de NumPy.matplotlib

### Perfil del alumno

Esta es una descripción general rápida de las matrices en NumPy. 

Muestra cómo se representan y se pueden manipular las matrices n-dimensionales (\(n>=2\)). 

En particular, si no sabe cómo aplicar funciones comunes a matrices n-dimensionales (sin usar for-loops), o si desea comprender las propiedades de eje y forma para matrices n-dimensionales, este artículo podría ser de ayuda.

### Objetivos de aprendizaje

Después de leer, usted debería ser capaz de:

* Comprender la diferencia entre matrices de una, dos y n dimensiones en NumPy;

* Comprender cómo aplicar algunas operaciones de álgebra lineal a matrices n-dimensionales sin usar for-loops;

* Comprender las propiedades de eje y forma de matrices n-dimensionales.

Lo básico
El objeto principal de NumPy es la matriz multidimensional homogénea. 

Es una tabla de elementos (generalmente números), todos del mismo tipo, indexados por una tupla de enteros no negativos. En NumPy las dimensiones se denominan ejes.

Por ejemplo, las coordenadas de un punto en el espacio 3D tienen un eje. 

Ese eje tiene 3 elementos, por lo que decimos que tiene una longitud de 3. 

En el ejemplo que se muestra a continuación, la matriz tiene 2 ejes. 

El primer eje tiene una longitud de 2, el segundo eje tiene una longitud de 3.

In [9]:
np.array([[1., 0., 0.],
 [0., 1., 2.]]) 

array([[1., 0., 0.],
       [0., 1., 2.]])

La clase de matriz de NumPy se llama ndarray

También se le conoce por el alias arraynumpy

Tenga en cuenta que no es lo mismo que la clase Standard Python Library, que solo maneja matrices unidimensionales y ofrece menos funcionalidad. Los atributos más importantes de un objeto son:

ndarray.ndim  
el número de ejes (dimensiones) de la matriz.

ndarray.shape    
las dimensiones de la matriz. Esta es una tupla de enteros que indica el tamaño de la matriz en cada dimensión. Para una matriz con n filas y m columnas, será `.shape(n,m)` La longitud de la tupla es, por lo tanto, el número de ejes, 

ndarray.size
el número total de elementos de la matriz. Esto es igual al producto de los elementos de .shape

ndarray.dtype
un objeto que describe el tipo de elementos de la matriz. Uno puede crear o especificar dtype's usando tipos estándar de Python. Además, NumPy proporciona tipos propios. numpy.int32, numpy.int16 y numpy.float64 son algunos ejemplos.

ndarray.itemsize
el tamaño en bytes de cada elemento de la matriz. Por ejemplo, una matriz de elementos de tipo tiene 8 (=64/8), mientras que una de tipo tiene 4 (=32/8). Es equivalente a .float64itemsizecomplex32itemsizendarray.dtype.itemsize

ndarray.data
el búfer que contiene los elementos reales de la matriz. Normalmente, no necesitaremos usar este atributo porque accederemos a los elementos de una matriz utilizando las instalaciones de indexación.

Un ejemplo

In [10]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
a.shape

(3, 5)

In [ ]:
a.ndim

In [12]:
a.dtype.name

'int32'

In [18]:
a.item 

<function ndarray.item>

In [19]:
a.itemsize     # retorna el tamaño de cada elemento en bytes 

4

In [14]:
a.size

15

In [15]:
type(a)

numpy.ndarray

In [20]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [21]:
type(b)


numpy.ndarray

## Creación de matrices o arreglos de numpy

Hay varias formas de crear matrices.

Por ejemplo, puede crear una matriz a partir de una **lista o tupla** normal de Python utilizando la función .array 

El tipo de matriz resultante se deduce del tipo de elementos en las secuencias

In [22]:
import numpy as np

In [23]:
a = np.array((2, 3, 4)) # matriz a partir de una tupla 

In [24]:
a

array([2, 3, 4])

In [26]:
a.dtype

dtype('int32')

In [27]:
b = np.array([1.2, 3.5, 5.1])     # matriz a partir de una lista 

In [28]:
b.dtype

dtype('float64')

Un error frecuente consiste en llamar con múltiples argumentos, en lugar de proporcionar una sola secuencia como argumento.array

In [29]:
>>> a = np.array(1, 2, 3, 4)    # WRONG

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [30]:
a = np.array([1, 2, 3, 4])  # RIGHT

`array` transforma secuencias de secuencias en matrices bidimensionales, secuencias de secuencias de secuencias en matrices tridimensionales, etc.

In [31]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

El tipo de matriz también se puede especificar explícitamente en el momento de la creación:

In [32]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

A menudo, los elementos de una matriz son originalmente desconocidos, pero se conoce su tamaño. 

Por lo tanto, NumPy ofrece varias funciones para crear matrices con contenido de marcador de posición inicial. 

Estos minimizan la necesidad de matrices en crecimiento, una operación costosa.

La función `np.zeros()`crea una matriz llena de ceros, 
* la función `np.ones()` crea una matriz llena de unos y 
* la función `np.empty()` crea una matriz cuyo contenido inicial es aleatorio y depende del estado de la memoria. 

De forma predeterminada, el tipo d de la matriz creada es float64, pero se puede especificar mediante el argumento de la palabra clave .zerosonesempty

In [33]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2, 3, 4), dtype=np.int16)

In [ ]:
np.empty((2, 3))
array([[3.73603959e-262, 6.02658058e-154, 6.55490914e-260],  # may vary
       [5.30498948e-313, 3.14673309e-307, 1.00000000e+000]])

Para crear secuencias de números, NumPy proporciona la función `matriz.arange` que es análoga a la función integrada `range()` de Python, pero devuelve una matriz. 

In [34]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [35]:
np.arange(0, 2, 0.3)     # it accepts float arguments


array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

Cuando se utiliza `arange` con argumentos de coma flotante, generalmente no es posible predecir el número de elementos obtenidos, debido a la precisión finita de coma flotante. 

Por este motivo, suele ser mejor utilizar la función `linspace` que recibe como argumento el número de elementos que queremos, en lugar del paso:

In [36]:
from numpy import pi

In [37]:
np.linspace(0, 2, 9)                   # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [38]:
x = np.linspace(0, 2 * pi, 100)        # useful to evaluate function at lots of points
f = np.sin(x)

## Presentación de las Matrices 

Al imprimir una matriz, NumPy la muestra de manera similar a las listas anidadas, pero con el siguiente diseño:

el último eje se imprime de izquierda a derecha,

el penúltimo se imprime de arriba a abajo,

el resto también se imprimen de arriba a abajo, con cada rebanada separada de la siguiente por una línea vacía.

Las matrices unidimensionales se imprimen como filas, las bidimensionales como matrices y las tridimensionales como listas de matrices.

In [39]:
a = np.arange(6)  

In [40]:
                  # 1d array
print(a)

[0 1 2 3 4 5]


In [41]:
b = np.arange(12).reshape(4, 3)     # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [42]:
c = np.arange(24).reshape(2, 3, 4)  # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Consulte a continuación para obtener más detalles sobre `.reshape()`

Si una matriz es demasiado grande para ser impresa, NumPy omite automáticamente la parte central de la matriz y solo imprime las esquinas:

In [43]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [44]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


## Operaciones básicas

Los operadores aritméticos en matrices se aplican elementalmente. Se crea una nueva matriz y se rellena con el resultado.