## Problema 

In [1]:
#tengo que poner cuantro matrices y de esas cuantro matrices generar otra matriz
import numpy as np
A = np.array([[1,2],[3,4]]) #creamos matrice A
B = np.array([[11,22],[3,47]]) #creamos matrice B
C = np.array([[18,25],[3,49]]) #creamos matrice C
D = np.array([[15,27],[32,44]]) #creamos matrice D
A #mostrando la lista


array([[1, 2],
       [3, 4]])

In [ ]:
B

array([[11, 22],
       [ 3, 47]])

In [ ]:
C

array([[18, 25],
       [ 3, 49]])

In [ ]:
D

array([[15, 27],
       [32, 44]])

In [ ]:
E = np.concatenate([A,B],1)
E

array([[ 1,  2, 11, 22],
       [ 3,  4,  3, 47]])

In [ ]:
F = np.concatenate([C,D],1)
F

array([[18, 25, 15, 27],
       [ 3, 49, 32, 44]])

In [ ]:
G = np.concatenate([E,F],0)
G

array([[ 1,  2, 11, 22],
       [ 3,  4,  3, 47],
       [18, 25, 15, 27],
       [ 3, 49, 32, 44]])

In [3]:
def matrizDeMatrices(A,B,C,D):
    '''
    Entrada: 
    Sale: 
    '''
    E = np.concatenate([A,B],1)
    F = np.concatenate([C,D],1)
    G = np.concatenate([E,F],0)
    return G  

In [4]:
matrizDeMatrices(A,B,C,D) 

array([[ 1,  2, 11, 22],
       [ 3,  4,  3, 47],
       [18, 25, 15, 27],
       [ 3, 49, 32, 44]])